require('dotenv').config;
const express = require('express');
const path = require('path');
const app = express();
const route = require('./route/index');
app.set('view engine', 'ejs');
app.set('views', path.join(__dirname, 'views'));
app.use(express.static('public'));
app.use(express.urlencoded({extended: true}));
app.use(express.json());
app.use(route);
app.listen(3000);